package pages.master;

import java.nio.file.Paths;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.assertions.PlaywrightAssertions;

import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import utils.TestData;

public class ClientPage 
{
	
	Browser browser;
	Page page;
	
	public void SetUp()
	{
	
	browser=Playwright.create().chromium().launch(new BrowserType.LaunchOptions().setHeadless(false).setSlowMo(300));
	page=browser.newPage();
	page.navigate(TestData.LoginUrl);
	page.locator("#CompanyUserId").fill(TestData.UserID);
	page.locator("#CompanyPassword").fill(TestData.Password);
	page.locator("#btnLogin").click();
	}
	
	@Given("user is on the Master Page")
	public void Master()
	{
		SetUp();
		page.locator("xpath=//a[text()='Master']").click();
		
	}
	@When("User clicks on Client Master")
	public void ClientMaster()
	{
		page.locator("xpath=//li[@class='dropdown li_master_Client']").click();
	}
	
	@And("user clicks create Client")
	public void ClientMasterDetail1()
	{
		page.locator("xpath=//a[@class='li_master_Client_Create']").click();
	}
	@Then("Enter create client page is visible")
	public void ClientMasterDetail2()
	{
		page.locator("xpath=//p[text()='Client Details ']").isVisible();
	}
	
	@Given("user is on the Client detail page")
	public void CreateClient()
	{
		page.locator("xpath=//p[text()='Client Details ']").isVisible();
	}
	
	@When("user selects Company code")
	public void CreateClientDetail1()
	{
		page.locator("#CompanyCode").selectOption("2000 TATA MOTORS LTD");
	}
	
	@Then("company name  and client code is autogenerated")
	public void CreateClientDetail2()
	{
		PlaywrightAssertions.assertThat(page.locator("#CompanyName")).not().isEmpty();
		PlaywrightAssertions.assertThat(page.locator("#ClientCode")).not().isEmpty();
	}
	
	@When("user enters Client name, selects Ownership Type,enters client website and chooses client logo and clicks on next button")
	public void CreateClientDetail3()
	{
		page.locator("#ClientName").fill("Sneha");
		page.locator("#OwnershipType").selectOption("Partnership Firms");
		page.locator("#ClientWebSite").fill("https://tcs.com");
		page.locator("#clientIcon").setInputFiles(Paths.get("D:\\prachi\\Analysis\\logo\\google-logo.png"));
		page.locator(".Client-next").first().click();
	}
	
	@Then("Client address page should be autofill and visible")
	public void CreateClientDetail4()
	{
		page.locator("xpath=//a[text()='Client Address']").isVisible();
		PlaywrightAssertions.assertThat(page.locator("#Client_Addr")).not().isEmpty();
	}
	@And("click on next button")
	public void NExtButton()
	{
		page.locator(".Client-next").nth(1).click();
	}
	
	
	
	
	
	
	
	
	
	
	

}
